language: python
python:
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagemagick

install:
  - "pip install -r requirements.txt"

# command to run tests
script: python manage.py test

notifications:
  email: false
